version: '3.0'

#volumes:
#  postgres_data:
#    driver: local

services:
  postgres:
    image: postgres
#    volumes:
#    - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
  keycloak:
    #image: jboss/keycloak:4.3.0.Final
    build: .
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak123
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      #KEYCLOAK_LOGLEVEL: DEBUG
      #ROOT_LOGLEVEL: DEBUG
      # Uncomment the line below if you want to specify JDBC parameters. The
      # parameter below is just an example, and it shouldn't be used in
      # production without knowledge. It is highly recommended that you read the
      # PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
    - "8111:8080"
    #- "8112:9990"
    - "7600:7600"
    - "45688:45688/udp"
    - "45700:45700"
    - "55200:55200/udp"

    depends_on:
    - postgres
